apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@globex.com
    picture: /api/proxy/user-avatars/svg?seed=guest
  memberOf: [globex-developers, lab-users]